---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	patient_data(patient_data)
	symptom_analysis(symptom_analysis)
	history_analysis(history_analysis)
	lab_analysis(lab_analysis)
	knowledge_retrieval(knowledge_retrieval)
	differential_diagnosis(differential_diagnosis)
	diagnostic_planning(diagnostic_planning)
	safety_review(safety_review)
	final_report(final_report)
	__end__([<p>__end__</p>]):::last
	__start__ --> patient_data;
	diagnostic_planning --> safety_review;
	differential_diagnosis --> diagnostic_planning;
	history_analysis --> knowledge_retrieval;
	knowledge_retrieval --> differential_diagnosis;
	lab_analysis --> knowledge_retrieval;
	patient_data -.-> final_report;
	patient_data -.-> history_analysis;
	patient_data -.-> lab_analysis;
	patient_data -.-> symptom_analysis;
	safety_review -.-> differential_diagnosis;
	safety_review -.-> final_report;
	symptom_analysis --> knowledge_retrieval;
	final_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
